variables:
  - name: TARGET_REPO
    default: ghcr.io/mxnxpx/packages/uds

  - name: FLAVOR
    default: upstream

  - name: VERSION
    description: "The version of the packages to build"
    # x-release-please-start-version
    default: "0.16.1"
    # x-release-please-end

tasks:
  - name: standard-package
    description: "Publish the UDS package"
    actions:
      - cmd: |
          uds zarf package publish build/zarf-package-core-amd64-${VERSION}.tar.zst oci://${TARGET_REPO}

          # dont publish arm64 for registry1 since IB images are only amd64
          if [ "${FLAVOR}" != "registry1" ]; then
            uds zarf package publish build/zarf-package-core-arm64-${VERSION}.tar.zst oci://${TARGET_REPO}
          fi

      - description: "Tag the latest package (if snapshot)"
        cmd: |
          if [ $(echo "${TARGET_REPO}" | grep 'snapshot') ]; then
             pkgPath="${TARGET_REPO}/core"
             latestTag="latest-snapshot"
             uds zarf tools registry copy ${pkgPath}:${VERSION}-${FLAVOR} ${pkgPath}:${latestTag}-${FLAVOR}
          fi

  - name: bundles
    description: "Publish UDS Bundles"
    actions:
      - description: "Publish amd64 and arm64 bundles"
        cmd: |
          uds publish bundles/k3d-standard/uds-bundle-k3d-*-amd64-${VERSION}.tar.zst oci://${TARGET_REPO}/bundles --no-progress
          uds publish bundles/k3d-standard/uds-bundle-k3d-*-arm64-${VERSION}.tar.zst oci://${TARGET_REPO}/bundles --no-progress

          uds publish bundles/k3d-istio/uds-bundle-k3d-*-arm64-${VERSION}.tar.zst oci://${TARGET_REPO}/bundles --no-progress
          uds publish bundles/k3d-istio/uds-bundle-k3d-*-amd64-${VERSION}.tar.zst oci://${TARGET_REPO}/bundles --no-progress

      - description: "Tag the latest bundles"
        cmd: |
          if [ $(echo "${TARGET_REPO}" | grep 'snapshot') ]; then
             latestTag="latest-snapshot"
          else
             latestTag="latest"
          fi
          pkgPath="${TARGET_REPO}/bundles/k3d-core-demo"
          uds zarf tools registry copy ${pkgPath}:${VERSION} ${pkgPath}:${latestTag}

          pkgPath="${TARGET_REPO}/bundles/k3d-core-istio-dev"
          uds zarf tools registry copy ${pkgPath}:${VERSION} ${pkgPath}:${latestTag}
