on:
  schedule:
    # Runs daily at 10:00 UTC
    - cron: "0 10 * * *"
  workflow_dispatch:
    inputs:
      snapshot:
        required: true
        default: 'true'
        type: string

name: snapshot-release-workflow

jobs:
  publish-snapshot-release:
    permissions:
      contents: write
      packages: write
    uses: ./.github/workflows/publish-workflow.yaml
    with:
      snapshot: 'true'
    secrets: inherit

  update-snapshot-latest-tag:
    needs: publish-snapshot-release
    env:
      GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Update snapshot-latest tag
        run: |
          if gh release view snapshot-latest; then
            gh release delete snapshot-latest --cleanup-tag -y
          fi
          gh release create snapshot-latest -t "snapshot-latest" -n "" --prerelease
